
//login types 
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

// signup types
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

// on_boarding
export const SET_ONBORADING = "FETCH_ONBORADING"
export const SET_ONBORADING_SUCCESS = "FETCH_ONBORADING_SUCCESS"
export const SET_ONBORADING_FAILURE = "FETCH_ONBORADING_FAILURE"



